### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1000
}

### Delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000000"
}

### Get
GET http://localhost:8080/account?user_id=1
